### ISSUE TITLE
Reading ome-zarr issue

### ISSUE THREAD

**Issue by jburel** [bcdev/jzarr#7]
I am trying to read a ome-zarr files available on embassy
https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001247.zarr

I wrote a little client download the zarr  locally and I attempted to read the file using jzarr v0.3
I got the following error when reading the file:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.bc.zarr.ZarrHeader` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (BufferedReader); line: 1, column: 2]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1592)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1058)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3227)
        at com.bc.zarr.ZarrUtils.fromJson(ZarrUtils.java:104)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:69)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:60)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:56)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:52)
        at com.example.Zarr.readZarrFile(Zarr.java:193)
```

**Comment by SabineEmbacher** [comment]
Dear Jean-Marie Burel,

1. Is what you downloaded a file or a directory with subdirectories?
     a. If it is a single file, you might have to unzip it first.

2. If it is a directory ...is there a file named ".zgroup" or ".zarray" in the directory?

3. Can you please show me the code snipped, how you try to open the Zarr Group or Array?

Best Regards
Sabine

**Comment by jburel** [comment]
It is a directory and there is a ``.zarray`` file.
If I do
```
File f = new File("PATH_TOFILE/6001247.zarr");
 ZarrArray opened = ZarrArray.open(f.getAbsolutePath());
```
I got the error mentioned above

If I do
```
File f = new File("PATH_TOFILE/6001247.zarr/.zarray");
 ZarrArray opened = ZarrArray.open(f.getAbsolutePath());
```
I got 
```
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:67)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:60)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:56)
        at com.bc.zarr.ZarrArray.open(ZarrArray.java:52)
        at com.example.Zarr.readZarrFile(Zarr.java:193)
        at com.example.Zarr.main(Zarr.java:207)
```

**Comment by SabineEmbacher** [comment]
Can you please send me the ".zarray" and ".zattrs" file?

**Comment by jburel** [comment]
The .zattrs is available at https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001247.zarr/.zattrs
and .zarray at https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001247.zarr/0/.zarray

**Comment by SabineEmbacher** [comment]
Dear Jean-Marie Burel,

in the directory https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001247.zarr/ I cannot find a `.zarray` but a `.zgroup` file.

That means this directory is the root node of the data, a so called zarr group, not a zarr array.
A group can contain `0-n` subgroups and `0-n` zarr arrays.

In this case, the main group contains exactly 1 data array named `0`.

You can open the main group with :
```
  ZarrGroup.open("pathToGroupDirectoryNotToThe.zgroupFile")
```
see: https://github.com/bcdev/jzarr/blob/master/src/main/java/com/bc/zarr/ZarrGroup.java#L57

The actual data and therefore the actual zarr array is located in the directory `0`.

The `.zarray` file in this directory says that `blosc` was used as compression algorithm for the data.

Unfortunately JZarr does not support `blosc` at the moment. The algorithm is already available, but unfortunately I did not find the time to integrate the algorithm yet. See: https://jzarr.readthedocs.io/en/latest/tutorial.html#compressors

Please watch the issue https://github.com/bcdev/jzarr/issues/8 if you want to be automatically notified when the algorithm is integrated.

Once JZarr supports `blosc` you could open the array almost as you tried before.
Only one correction: The `0` has to be added in the path (see arrow below).
```
                                              |
                                             \|/
                                              V
  File f = new File("PATH_TOFILE/6001247.zarr/0/");
  ZarrArray opened = ZarrArray.open(f.getAbsolutePath());
```

Best Regards
Sabine

**Comment by jburel** [comment]
you are correct I was looking in the "0" resolution folder.
I will close this issue and wait for the support for ``blosc``.
Do you have timeline?

**Comment by SabineEmbacher** [comment]
Yesterday I spoke with my supervisor. We plan to implement the blosc support until the end of November.

**Comment by jburel** [comment]
Great I will watch #8. Do not hesitate to ping me on issue #8. We are developing tools to access zarr files.

**Comment by SabineEmbacher** [comment]
Dear Jean-Marie Burel,

The blosc compression is now ready for use.
The documentation is still to be worked on.

Have fun trying it out ! 
If there are any problems, you are welcome to contact me.

Best Regards
Sabine

**Comment by jburel** [comment]
@SabineEmbacher great thanks
